export type ShaderNodeType =
  | 'output'
  | 'color'
  | 'texture'
  | 'mix'
  | 'multiply'
  | 'add'
  | 'subtract'
  | 'vector'
  | 'normal'
  | 'uv';

export interface ShaderNodeSocket {
  id: string;
  name: string;
  type: 'float' | 'vec2' | 'vec3' | 'vec4';
}

export interface ShaderNode {
  id: string;
  type: ShaderNodeType;
  title: string;
  x: number;
  y: number;
  inputs: ShaderNodeSocket[];
  outputs: ShaderNodeSocket[];
  params: Record<string, any>;
}

export interface ShaderConnection {
  fromNodeId: string;
  fromSocketId: string;
  toNodeId: string;
  toSocketId: string;
}

export interface MaterialGraph {
  nodes: ShaderNode[];
  connections: ShaderConnection[];
}

let nodeIdCounter = 1;

const NODE_DEFS: Record<
  Exclude<ShaderNodeType, 'output'>,
  { title: string; inputs: [string, string][]; outputs: [string, string][] }
> = {
  color: { title: 'Color', inputs: [], outputs: [['color', 'vec4']] },
  texture: { title: 'Texture', inputs: [['uv', 'vec2']], outputs: [['rgba', 'vec4']] },
  mix: {
    title: 'Mix',
    inputs: [['A', 'vec4'], ['B', 'vec4'], ['Factor', 'float']],
    outputs: [['result', 'vec4']],
  },
  multiply: { title: 'Multiply', inputs: [['A', 'vec4'], ['B', 'vec4']], outputs: [['result', 'vec4']] },
  add: { title: 'Add', inputs: [['A', 'vec4'], ['B', 'vec4']], outputs: [['result', 'vec4']] },
  subtract: { title: 'Subtract', inputs: [['A', 'vec4'], ['B', 'vec4']], outputs: [['result', 'vec4']] },
  vector: { title: 'Vector', inputs: [], outputs: [['xyz', 'vec3']] },
  normal: { title: 'Normal', inputs: [], outputs: [['normal', 'vec3']] },
  uv: { title: 'UV', inputs: [], outputs: [['uv', 'vec2']] },
};

export function createNode(type: ShaderNodeType, x = 40, y = 40): ShaderNode {
  if (type === 'output') {
    return {
      id: `n${nodeIdCounter++}`,
      type: 'output',
      title: 'Output',
      x,
      y,
      inputs: [['surface', 'vec4'] as [string, string]].map(([name, t]) => ({ id: name.toLowerCase(), name, type: t as any })),
      outputs: [],
      params: {},
    };
  }
  const def = NODE_DEFS[type];
  return {
    id: `n${nodeIdCounter++}`,
    type,
    title: def.title,
    x,
    y,
    inputs: def.inputs.map(([name, t]) => ({ id: name.toLowerCase(), name, type: t as any })),
    outputs: def.outputs.map(([name, t]) => ({ id: name.toLowerCase(), name, type: t as any })),
    params: {},
  };
}

export function createDefaultGraph(): MaterialGraph {
  return {
    nodes: [createNode('output', 320, 100)],
    connections: [],
  };
}

export function canConnect(
  graph: MaterialGraph,
  fromNodeId: string,
  fromSocketId: string,
  toNodeId: string,
  toSocketId: string,
): boolean {
  const fromNode = graph.nodes.find((n) => n.id === fromNodeId);
  const toNode = graph.nodes.find((n) => n.id === toNodeId);
  if (!fromNode || !toNode) return false;

  const fromSock = fromNode.outputs.find((s) => s.id === fromSocketId);
  const toSock = toNode.inputs.find((s) => s.id === toSocketId);
  if (!fromSock || !toSock) return false;

  // vec3 -> vec4 is allowed (implicit w=1), float -> anything allowed (scalar broadcast)
  if (fromSock.type === toSock.type) return true;
  if (fromSock.type === 'float') return true;
  if (toSock.type === 'float') return false;
  if (fromSock.type === 'vec3' && toSock.type === 'vec4') return true;
  if (fromSock.type === 'vec2' && toSock.type !== 'vec2') return false;
  if (fromSock.type === 'vec3' && toSock.type === 'vec2') return false;
  return false;
}

export function addConnection(
  graph: MaterialGraph,
  fromNodeId: string,
  fromSocketId: string,
  toNodeId: string,
  toSocketId: string,
): boolean {
  if (!canConnect(graph, fromNodeId, fromSocketId, toNodeId, toSocketId)) return false;
  // Remove existing connection to the same input
  graph.connections = graph.connections.filter(
    (c) => !(c.toNodeId === toNodeId && c.toSocketId === toSocketId),
  );
  graph.connections.push({ fromNodeId, fromSocketId, toNodeId, toSocketId });
  return true;
}

export function removeNodeFromGraph(graph: MaterialGraph, nodeId: string): void {
  graph.nodes = graph.nodes.filter((n) => n.id !== nodeId);
  graph.connections = graph.connections.filter(
    (c) => c.fromNodeId !== nodeId && c.toNodeId !== nodeId,
  );
}

export function compileGraph(graph: MaterialGraph): string {
  const lines: string[] = [
    '// Generated by NOISE3D Node Material Editor',
    '#version 300 es',
    'precision highp float;',
    '',
    'in vec2 vUV;',
    'in vec3 vNormal;',
    'out vec4 fragColor;',
    '',
  ];

  // Find output node
  const outputNode = graph.nodes.find((n) => n.type === 'output');
  if (!outputNode) {
    lines.push('void graphMain() {}');
    return lines.join('\n');
  }

  // Topologically evaluate nodes via DFS from output
  const evaluated = new Set<string>();
  const bodyLines: string[] = [];

  const evalNode = (nodeId: string): string | null => {
    if (evaluated.has(nodeId)) return nodeId;
    const node = graph.nodes.find((n) => n.id === nodeId);
    if (!node) return null;
    evaluated.add(nodeId);

    for (const input of node.inputs) {
      const conn = graph.connections.find(
        (c) => c.toNodeId === node.id && c.toSocketId === input.id,
      );
      if (conn) {
        evalNode(conn.fromNodeId);
      }
    }

    switch (node.type) {
      case 'color': {
        const r = node.params.r ?? 1;
        const g = node.params.g ?? 1;
        const b = node.params.b ?? 1;
        bodyLines.push(`vec4 ${node.id}_out = vec4(${r}, ${g}, ${b}, 1.0);`);
        break;
      }
      case 'vector':
        bodyLines.push(`vec3 ${node.id}_out = vec3(${node.params.x ?? 0}, ${node.params.y ?? 0}, ${node.params.z ?? 0});`);
        break;
      case 'uv':
        bodyLines.push(`vec2 ${node.id}_out = vUV;`);
        break;
      case 'normal':
        bodyLines.push(`vec3 ${node.id}_out = normalize(vNormal);`);
        break;
      case 'mix': {
        const a = getInputRef(node, 'a');
        const b = getInputRef(node, 'b');
        const f = getInputRef(node, 'factor');
        bodyLines.push(`vec4 ${node.id}_out = mix(${a}, ${b}, clamp(${f}, 0.0, 1.0));`);
        break;
      }
      case 'multiply': {
        const a = getInputRef(node, 'a');
        const b = getInputRef(node, 'b');
        bodyLines.push(`vec4 ${node.id}_out = ${a} * ${b};`);
        break;
      }
      case 'add': {
        const a = getInputRef(node, 'a');
        const b = getInputRef(node, 'b');
        bodyLines.push(`vec4 ${node.id}_out = ${a} + ${b};`);
        break;
      }
      case 'subtract': {
        const a = getInputRef(node, 'a');
        const b = getInputRef(node, 'b');
        bodyLines.push(`vec4 ${node.id}_out = ${a} - ${b};`);
        break;
      }
      default:
        break;
    }
    return node.id;
  };

  const getInputRef = (node: ShaderNode, socketId: string): string => {
    const conn = graph.connections.find(
      (c) => c.toNodeId === node.id && c.toSocketId === socketId,
    );
    if (!conn) {
      // Default values per socket type
      const input = node.inputs.find((i) => i.id === socketId);
      if (input?.type === 'float') return '0.5';
      return 'vec4(0.5)';
    }
    const fromType = graph.nodes.find((n) => n.id === conn.fromNodeId)?.outputs.find((o) => o.id === conn.fromSocketId)?.type;
    const ref = `${conn.fromNodeId}_out`;
    const targetInput = node.inputs.find((i) => i.id === socketId);
    if (fromType === 'vec3' && targetInput?.type === 'vec4') return `vec4(${ref}, 1.0)`;
    if (fromType !== 'float' && targetInput?.type === 'float') return `${ref}.x`;
    if (fromType === 'float' && targetInput?.type !== 'float') return `vec4(${ref})`;
    return ref;
  };

  if (outputNode.inputs[0]) {
    const surfaceConn = graph.connections.find(
      (c) => c.toNodeId === outputNode.id && c.toSocketId === outputNode.inputs[0].id,
    );
    if (surfaceConn) {
      evalNode(surfaceConn.fromNodeId);
      const ref = getInputRef(outputNode, outputNode.inputs[0].id);
      bodyLines.push(`fragColor = ${ref};`);
    } else {
      bodyLines.push('fragColor = vec4(0.5);');
    }
  }

  lines.push('void graphMain() {');
  lines.push(...bodyLines.map((l) => '  ' + l));
  lines.push('}');
  return lines.join('\n');
}
